# Generated by Django 2.1.4 on 2019-01-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.SlugField(max_length=30),
        ),
    ]
