# Generated by Django 2.1.4 on 2019-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipal_name', models.CharField(max_length=150)),
                ('person_in_charge', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'municipal',
            },
        ),
    ]
